<?php

return [
    'announcement' => 'Duyuru',
    'application' => 'Başvuru',
    'blog_category' => 'Blog Kategori',
    'blog' => 'Blog',
    'catalog' => 'Katalog',
    'catalog_category' => 'Katalog Kategori',
    'contact_messages' => 'İletişim Mesajları',
    'contact_people' => 'İletişim Kişileri',
    'customer_comment' => 'Müşteri Yorumları',
    'faq_category' => 'Soru Kategori',
    'faq' => 'Sıkça Sorulan Soru',
    'file' => 'Dosya Yönetici',
    'locale' => 'Dil',
    'milestone' => 'Tarihçe',
    'news_category' => 'Haber Kategori',
    'news' => 'Haber',
    'newsletter' => 'Bülten',
    'page' => 'Sayfa',
    'photo_category' => 'Fotoğraf Kategori',
    'photo' => 'Fotoğraf',
    'product_category' => 'Ürün Kategori',
    'product' => 'Ürün',
    'project_category' => 'Proje Kategori',
    'project' => 'Proje',
    'reference' => 'Referans',
    'role_group' => 'Yetki Grubu',
    'service_category' => 'Hizmet Kategori',
    'service' => 'Hizmet',
    'setting' => 'Ayarlar',
    'slider' => 'Slider',
    'team_category' => 'Ekip Kategori',
    'team' => 'Ekip',
    'user' => 'Kullanıcı',
    'video_category' => 'Video Kategori',
    'video' => 'Video',
];
